import { ROUTES } from "./routes";

export const NAV_ITEMS = [
  { label: "หน้าหลัก", href: ROUTES.HOME, id: "home" },
  { label: "การจองของฉัน", href: ROUTES.BOOKING, id: "booking", login: true },
  { label: "Dashboard", href: ROUTES.DASHBOARD, id: "admin", adminOnly: true },
];

export const AUTHUSER = {
  id: "user_01",
  firstName: "สมชาย",
  lastName: "สายลุย",
  email: "admin@ticketspace.com",
  role: "ADMIN",
  createdAt: "2025-12-20T08:00:00.000Z",
};

export const LOCATIONS = [
  {
    id: "1234",
    item: 1,
    name: "วัดพระศรีรัตนศาสดาราม (วัดพระแก้ว)",
    typeNumber: 1,
    typeName: "ถ้ำ",
    subdistrict: "พระบรมมหาราชวัง",
    district: "พระนคร",
    province: "กรุงเทพมหานคร",
    region: "กลาง",
    latitude: 13.7516,
    longitude: 100.4927,
    importance: "วัดคู่บ้านคู่เมืองของประเทศไทย",
    details: "ประดิษฐานพระพุทธมหามณีรัตนปฏิมากร (พระแก้วมรกต)",
    limitBooking: 500,
  },
  {
    id: "5648",
    item: 2,
    name: "อุทยานแห่งชาติเขาใหญ่",
    typeNumber: 2,
    typeName: "ชายหาด",
    subdistrict: "หมูสี",
    district: "ปากช่อง",
    province: "นครราชสีมา",
    region: "ตะวันออกเฉียงเหนือ",
    latitude: 14.4392,
    longitude: 101.3723,
    importance: "มรดกโลกทางธรรมชาติ",
    details: "มีน้ำตกเหวสุวัตและเหวนรก เป็นแหล่งเดินป่าศึกษาธรรมชาติ",
    limitBooking: 300,
  },
  {
    id: "9102",
    item: 3,
    name: "ยอดดอยอินทนนท์",
    typeNumber: 2,
    typeName: "เกาะ",
    subdistrict: "บ้านหลวง",
    district: "จอมทอง",
    province: "เชียงใหม่",
    region: "เหนือ",
    latitude: 18.5912,
    longitude: 98.4871,
    importance: "จุดที่สูงที่สุดในประเทศไทย",
    details: "อากาศหนาวเย็นตลอดปี มีเส้นทางศึกษาธรรมชาติกิ่วแม่ปาน",
    limitBooking: 200,
  },
  {
    id: "3598",
    item: 4,
    name: "อุทยานแห่งชาติหมู่เกาะสิมิลัน",
    typeNumber: 3,
    typeName: "ภูเขา",
    subdistrict: "เกาะพระทอง",
    district: "คุระบุรี",
    province: "พังงา",
    region: "ใต้",
    latitude: 8.6465,
    longitude: 97.6449,
    importance: "แหล่งดำน้ำติดอันดับโลก",
    details: "น้ำใสหาดทรายขาวละเอียด มีหินเรือใบที่เป็นสัญลักษณ์",
    limitBooking: 150,
  },
  {
    id: "7625",
    item: 5,
    name: "พระปฐมเจดีย์",
    typeNumber: 1,
    typeName: "น้ำตก",
    subdistrict: "พระปฐมเจดีย์",
    district: "เมืองนครปฐม",
    province: "นครปฐม",
    region: "กลาง",
    latitude: 13.8196,
    longitude: 100.0601,
    importance: "เจดีย์ที่ใหญ่ที่สุดในประเทศไทย",
    details: "ประดิษฐานพระบรมสารีริกธาตุขององค์สมเด็จพระสัมมาสัมพุทธเจ้า",
    limitBooking: 400,
  },
  {
    id: "4826",
    item: 6,
    name: "ถนนคนเดินท่าแพ",
    typeNumber: 4,
    typeName: "ธรณีสัณฐานและภูมิลักษณวรรณา",
    subdistrict: "ศรีภูมิ",
    district: "เมืองเชียงใหม่",
    province: "เชียงใหม่",
    region: "เหนือ",
    latitude: 18.7877,
    longitude: 98.9932,
    importance: "แหล่งรวมสินค้าพื้นเมืองและศิลปวัฒนธรรม",
    details: "เปิดทุกวันอาทิตย์ ตั้งแต่ประตูท่าแพไปตามถนนราชดำเนิน",
    limitBooking: 1000,
  },
];

export const LOCATION_IMAGES: Record<string, string> = {
  ชายหาด: "/images/beach.jpg",
  ซากดึกดำบรรพ์: "/images/fossils.jpg",
  ถ้ำ: "/images/cave.jpg",
  ธรณีสัณฐานและภูมิลักษณวรรณา: "/images/forest.jpg",
  น้ำตก: "/images/waterfall.jpg",
  ภูเขา: "/images/mountain.jpg",
  เกาะ: "/images/island.jpg",
  แก่ง: "/images/rapids.jpg",
  แหล่งน้ำ: "/images/river.jpg",
  โป่งน้ำพุร้อน: "/images/hot-spring.jpg",
};

export const LOCATION_PRICES: Record<string, number> = {
  ชายหาด: 50,
  ซากดึกดำบรรพ์: 80,
  ถ้ำ: 100,
  ธรณีสัณฐานและภูมิลักษณวรรณา: 60,
  น้ำตก: 40,
  ภูเขา: 120,
  เกาะ: 200,
  แก่ง: 70,
  แหล่งน้ำ: 30,
  โป่งน้ำพุร้อน: 150,
};

export const BOOKINGS = [
  {
    id: "kmsjklfjsiofj",
    numOfPeople: 2,
    bookingDate: new Date("2025-12-30"),
    totalPrice: 200.0,
    remarks: "ขอไกด์นำเที่ยวที่พูดภาษาอังกฤษได้",
    locationId: "loc_cave_01",
    userId: "user_01",
    createdAt: new Date(),
    updatedAt: new Date(),
    // เพิ่มข้อมูล Location
    location: {
      id: "loc_cave_01",
      name: "ถ้ำหลวงขุนน้ำนางนอน",
      typeName: "ถ้ำ",
      imageUrl: "/images/cave.jpg",
    },
  },
  {
    id: "bk_002",
    numOfPeople: 5,
    bookingDate: new Date("2026-01-05"),
    totalPrice: 250.0,
    remarks: "มีผู้สูงอายุและรถเข็น",
    locationId: "loc_beach_01",
    userId: "user_02",
    createdAt: new Date(),
    updatedAt: new Date(),
    location: {
      id: "loc_beach_01",
      name: "หาดไร่เลย์",
      typeName: "ชายหาด",
      imageUrl: "/images/beach.jpg",
    },
  },
  {
    id: "bk_003",
    numOfPeople: 1,
    bookingDate: new Date("2026-01-10"),
    totalPrice: 150.0,
    remarks: null,
    locationId: "loc_hotspring_01",
    userId: "user_01",
    createdAt: new Date(),
    updatedAt: new Date(),
    location: {
      id: "loc_hotspring_01",
      name: "น้ำพุร้อนฝาง",
      typeName: "โป่งน้ำพุร้อน",
      imageUrl: "/images/hot-spring.jpg",
    },
  },
  {
    id: "bk_004",
    numOfPeople: 10,
    bookingDate: new Date("2026-02-14"),
    totalPrice: 2000.0,
    remarks: "จองในนามบริษัท ออกใบกำกับภาษี",
    locationId: "loc_island_01",
    userId: "user_03",
    createdAt: new Date(),
    updatedAt: new Date(),
    location: {
      id: "loc_island_01",
      name: "เกาะพีพี",
      typeName: "เกาะ",
      imageUrl: "/images/island.jpg",
    },
  },
];
